apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml
  - service-headless.yaml
  - hpa.yaml

labels:
  - pairs:
      app.kubernetes.io/name: tag
    includeSelectors: true

images:
  - name: tigrisdata/tag
    newTag: v1.5.0
