apiVersion: v1
kind: Service
metadata:
  name: tag
  labels:
    app: tag
  annotations:
    # For AWS NLB
    # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # For GCP
    # cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  selector:
    app: tag
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
